controller_manager:
  ros__parameters:
    update_rate: 50
    ackermann_drive_controller:
      type: ackermann_steering_controller/AckermannSteeringController
      left_wheel_names:
        - rear_left_wheel_joint
      right_wheel_names:
        - rear_right_wheel_joint
      front_steering_left:
        - front_left_wheel_joint
      front_steering_right:
        - front_right_wheel_joint
      wheel_separation: 0.5  # Distance between front and rear axles
      wheel_base: 1.2       # Distance between left and right wheels
      cmd_vel_timeout: 0.5  # Timeout for /cmd_vel commands
      velocity_rolling_window_size: 10
